### ISSUE TITLE
How am I supposed to use this parser in prettier vscode?

### ISSUE THREAD

**Issue by ghost** [handlebars-lang/handlebars-parser#7]
Hello there, hope you are fine.

I was wondering how I am supposed to use this parser in the prettier.
Unfortunately, there are no instructions in the README file. 

The prettier *glimmer* parser was a complete nuisance in formatting .hbs files, having many flaws and bugs.
It didn't support using partials syntax, parent context notation. And it did also change single quotes within doubles quotes of attributes. 
Hope the parser you have provided does not have the aforementioned bugs.

Thanks!

**Comment by jaylinski** [comment]
Is this still relevant? The Prettier handlebars formatter improved a lot since last year.

**Comment by jaylinski** [comment]
If this is still relevant, please open a new issue.
